### ISSUE TITLE
Use jQuery 2

### ISSUE THREAD

**Issue by sylouuu** [Grafikart/Tracky#3]
Hi,

As this is a Chrome extension, you can use jQuery 2 instead of jQuery 1.

Bests

**Comment by Grafikart** [comment]
Indeed nice suggestion. I'll include this in the next commit

**Comment by sylouuu** [comment]
So, why do you need jQuery here?

**Comment by Grafikart** [comment]
I need it for jquery autocomplete that is triggered when you enter a project name or task. I know it's an overkill but It saved me time ^^

**Comment by sylouuu** [comment]
Okay, it could be a nice enhancement to remove jQuery and create your own autocomplete directive. :)

**Comment by Grafikart** [comment]
I'll add it to the todolist ^^
